on:
  push:

env:
  CI: true

jobs:
  get-lts:
    runs-on: ubuntu-latest
    steps:
      - id: get
        uses: msimerson/node-lts-versions@v1
    outputs:
      lts: ${{ steps.get.outputs.lts }}
      active: ${{ steps.get.outputs.active }}

  check-output:
    needs: get-lts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: ${{ fromJson(needs.get-lts.outputs.active) }}
      fail-fast: false
    steps:
      - uses: actions/setup-node@v4
        name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
        with:
          node-version: ${{ matrix.node-version }}
