on:
  push:

env:
  CI: true
  node-version: 16

jobs:
  get-lts:
    runs-on: ubuntu-latest
    steps:
      - name: Node LTS versions
        uses: msimerson/node-lts-versions@v1.1.1
    outputs:
      lts: ${{ steps.get-lts.outputs.lts }}

  check-output:
    needs: get-lts
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node-version: ${{ fromJson(needs.get-lts.outputs.lts) }}
      fail-fast: false

    - uses: actions/setup-node@v3
      name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
      with:
        node-version: ${{ matrix.node-version }}
