on:
  push:

env:
  CI: true
  node-version: 16

jobs:
  get-lts:
    runs-on: ubuntu-latest
    steps:
      - id: get-tls
        run: echo "::set-output name=lts::{[\"14\",\"16\"]}"
        # name: Node LTS versions
        # uses: msimerson/node-lts-versions@v1.1.1
    outputs:
      matrix: ${{ steps.get-tls.outputs.lts }}

  check-output:
    needs: get-lts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node-version: ${{ fromJson(needs.get-lts.outputs.matrix) }}
      fail-fast: false
    steps:
    - uses: actions/setup-node@v3
      name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
      with:
        node-version: ${{ matrix.node-version }}

