name: Test Coverage

on:
  workflow_call:
  push:
    branches: [main]

env:
  CI: true
  NODE_ENV: cov

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - run: npm install
      - run: npm run test:coverage:lcov || npm run test:coverage
      - uses: codecov/codecov-action@v2
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
