name: Lint

on:
  workflow_call:

env:
  CI: true
  node-version: lts/*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        name: Node ${{ env.node-version }}
        with:
          node-version: ${{ env.node-version }}

      - uses: actions/checkout@v4

      - run: npm install

      - run: npm run lint
