name: publish

on:
  workflow_call:

env:
  CI: true
  node-version: lts/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v6
        name: Node ${{ env.node-version }}
        with:
          node-version: ${{ env.node-version }}
      - uses: actions/checkout@v6
      - run: npm install
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/setup-node@v6
        name: Node ${{ env.node-version }}
        with:
          node-version: ${{ env.node-version }}
          registry-url: https://registry.npmjs.org/
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          # fetch-depth 0 needed by GitHub Release
      - run: npm publish --access=public

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: '@nictool'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
