name: publish

on:
  workflow_call:

env:
  CI: true
  node-version: 16

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        name: Node ${{ env.node-version }}
        with:
          node-version: ${{ env.node-version }}
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test


  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        name: Node ${{ env.node-version }}
        with:
          node-version: ${{ env.node-version }}
          registry-url: https://registry.npmjs.org/

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # fetch-depth 0 needed by GitHub Release

      - name: publish to NPM
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: GitHub Release
        uses: justincy/github-action-npm-release@2.0.1
        id: release

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: "@nictool"
      # - name: rename package with @nictool scope
      #   run: |
      #     echo "import fs from 'fs'" > gpr.js
      #     echo "const pkg = JSON.parse(fs.readFileSync('./package.json'))" >> gpr.js
      #     echo "pkg.name = \`@nictool/\${pkg.name}\`" >> gpr.js
      #     echo "fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2))" >> gpr.js
      #     node gpr.js
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
