name: Test

on:
  workflow_call:

jobs:
  test:
    needs: get-lts
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: ${{ fromJson(needs.get-lts.outputs.lts) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test

  test-active:
    # only test on the active LTS version, to save resources
    needs: get-lts
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        node-version: ${{ fromJson(needs.get-lts.outputs.active) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test

  get-lts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - id: get
        uses: msimerson/node-lts-versions@v1
    outputs:
      lts: ${{ steps.get.outputs.lts }}
      active: ${{ steps.get.outputs.active }}
